version: '3.8'
services:
selenium-hub:
image: selenium/hub:4.8.0-2023-10-17
container_name: selenium-hub
ports:
- '4444:4444'


chrome:
  image: selenium/node-chrome:4.8.0-2023-10-17
  depends_on:
  - selenium-hub
  environment:
  - SE_EVENT_BUS_HOST=selenium-hub
  volumes:
  - /dev/shm:/dev/shm


mysql:
  image: mysql:8.0
  environment:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: demo
  ports:
  - '3306:3306'


mongo:
  image: mongo:6
  ports:
  - '27017:27017'